<!-- Social media icons line Start -->

<div class="sm-handle">

    <!-- Twitter -->
    <a id="Twitter" class="sm-button" style="background-color: #55acee;" href="https://twitter.com/influnias" role="button"><i class="fa-brands fa-twitter" style="color: #ffffff;"></i></a>

    <!-- Instagram -->
    <a id="Instagram" class="sm-button" style="background-color: #ac2bac;" href="https://www.instagram.com/influnias/" role="button"><i class="fa-brands fa-instagram" style="color: #ffffff;"></i></a>

    <!-- Linkedin -->
    <a id="Linkedin" class="sm-button" style="background-color: #0082ca;" href="https://www.linkedin.com/authwall?trk=bf&trkInfo=AQHUchZzdRlmXQAAAYuE2AroQZtfUS6x-GOM-qrHiZjDkJA8YyN1_eQmIKeOO0UXcIqAbgQNLilihezkWF4iOXu3ADgY5C--g79wnh6cQTVXSxDM3cqy2AC1_uBBreq-ZbSLihs=&original_referer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Finflunias" role="button"><i class="fa-brands fa-linkedin" style="color: #ffffff;"></i></a>

    <!-- Youtube -->
    <a id="youtube" class="sm-button" style="background-color: #c4302b;" href="https://www.youtube.com/channel/UCm0ASpIy2CJsS9hzVedo_yg" role="button"><i class="fa-brands fa-youtube" style="color: #ffffff;"></i></a>

    <!-- Twitch -->
    <a id="Twitch" class="sm-button" style="background-color: #6441a5;" href="https://www.twitch.tv/influnias" role="button"><i class="fa-brands fa-twitch" style="color: #ffffff;"></i></i></a>

    <!-- Github -->
    <a id="Github" class="sm-button" style="background-color: #333333;" href="https://github.com/Influnias" role="button"><i class="fa-brands fa-github" style="color: #ffffff;"></i></a>

    <!-- Mail -->
    <a id="Mail" class="sm-button" style="background-color: #FFA500;" href="mailto:officiel@tyrolium.fr" role="button"><i class="fa-solid fa-envelope" style="color: #ffffff;"></i></i></a>


</div>

<!-- Social media icons line Start -->

<a class="terms" href="terms.php">Mentions légales</a>

<style>
    .terms{
        color: #e3e3e3;
        font-size: 12px;
    }
    .terms:hover{
        color: #a66ce1;
        text-decoration: underline;
    }
    .sm-handle {

        margin-bottom: 10px;

    }
</style>

<!-- copyright area -->

<p class="copyright">&copy Copyright 2017-2025 | All Rights Reserved by <a class="text-primary" href="https://tyrolium.fr">Tyrolium</a></p>