<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <div class="section-title text-center">
                <h3>FONDATEUR</h3>
            </div>
        </div>
    </div>
</div>
<div class="testimonials">
    <input type="radio" name="testimonial" id="input-testimonial1" checked>
    <!-- <input type="radio" name="testimonial" id="input-testimonial2">
            <input type="radio" name="testimonial" id="input-testimonial3"> -->
    <input type="radio" name="testimonial" id="input-testimonial4">
    <div class="testimonials-inner">
        <div class="testimonial">
            <div class="testimonial-photo">
                <div class="photo-background"></div>
                <div class="photo-author"></div>
            </div>
            <div class="testimonial-text">
                <p>J'ai eu envie de créer un projet qui revolutionnera l'influence et l'art sur internet en France, aujourd'hui c'est chose faite.</p>
            </div>
            <div class="testimonial-author">Maxime Tournier</div>
        </div>
        <!-- <div class="testimonial">
                    <div class="testimonial-photo">
                        <div class="photo-background"></div>
                        <div class="photo-author"></div>
                    </div>
                    <div class="testimonial-text">
                        <p>aaaaaaaaaaaaa</p>
                    </div>
                    <div class="testimonial-author">Maëwan Marthelot</div>
                </div>
                <div class="testimonial">
                    <div class="testimonial-photo">
                        <div class="photo-background"></div>
                        <div class="photo-author"></div>
                    </div>
                    <div class="testimonial-text">
                        <p>Two of my friends have never met each other. Before they spoke, I told both of them that the other is a bit deaf. They shouted at each other for a few minutes before they realized that I'm an asshole.</p>
                    </div>
                    <div class="testimonial-author">Doodle Wobblepants</div>
                </div> -->
        <div class="testimonial">
            <div class="testimonial-photo">
                <div class="photo-background"></div>
                <div class="photo-author"></div>
            </div>
            <div class="testimonial-text">
                <p>J’ai grandi avec l’idée de créer et partager… Alors pourquoi pas vous ? Une passion est une source infini de motivation alors voilà la nôtre.</p>
            </div>
            <div class="testimonial-author">Maëwan Marthelot</div>
        </div>
    </div>
    <div class="testimonials-arrows">
        <div class="arrow arrow-left">
            <label for="input-testimonial1"></label>
            <!-- <label for="input-testimonial2"></label>
                    <label for="input-testimonial3"></label> -->
            <label for="input-testimonial4"></label>
            <span></span>
        </div>
        <div class="arrow arrow-right">
            <label for="input-testimonial1"></label>
            <!-- <label for="input-testimonial2"></label>
                    <label for="input-testimonial3"></label> -->
            <label for="input-testimonial4"></label>
            <span></span>
        </div>
    </div>
    <div class="testimonials-bullets">
        <label for="input-testimonial1">
            <div class="bullet">
                <div>
                    <span></span>
                </div>
            </div>
        </label>
        <!-- <label for="input-testimonial2">
                    <div class="bullet">
                        <div>
                            <span></span>
                        </div>
                    </div>
                </label>
                <label for="input-testimonial3">
                    <div class="bullet">
                        <div>
                            <span></span>
                        </div>
                    </div>
                </label> -->
        <label for="input-testimonial4">
            <div class="bullet">
                <div>
                    <span></span>
                </div>
            </div>
        </label>
    </div>
</div>