<div class="container">
    <form id="contactus" action="https://tyrolium.fr/Contenu/Php/api/influnias/api.php" method="post">
        <h3>CONTACTEZ-NOUS</h3>
        <fieldset> <input name="influnias-name" placeholder="Nom" type="text" tabindex="1" required> </fieldset>
        <fieldset> <input name="influnias-email" placeholder="Email" type="email" tabindex="2" required> </fieldset>
        <fieldset> <textarea name="influnias-text" placeholder="Tapez votre message ici..." tabindex="5" required></textarea> </fieldset>
        <fieldset> <button name="submit" type="submit" id="contactus-submit" data-submit="...Sending"><i id="icon" class=""></i>Envoyer</button> </fieldset>
    </form>
</div>