<!-- Container -->
<div class="container">
    <!-- Section title -->
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <div class="section-title text-center">
                <h3>SERVICES</h3>
                <p class="desc">Vous devenez "Influnias Creator" et vous avez accès à cette liste à vie pendant toute la durée de votre abonnement.</p>
            </div>
        </div>
    </div>
    <div class="row" style="row-gap: 20px;">
        <!-- Service 1 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-camera" style="color: #ffffff;"></i></div>
                <h5>Production Créative</h5>
                <p class="desc">Organisation de shootings photo, gros tournages, et services vidéo complets, et recherche de lieux de tournage.</p>
            </div>
        </div>
        <!-- Service 2 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0.3s">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-gear" style="color: #ffffff;"></i></div>
                <h5>Gestion de Projets</h5>
                <p class="desc">Accompagnement de projets majeurs, planification d'événements pour créateurs, et facilitation des recrutements dans divers domaines.</p>
            </div>
        </div>
        <!-- Service 3 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0.6s">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-bullhorn" style="color: #ffffff;"></i></div>
                <h5>Aide à la Visibilité</h5>
                <p class="desc">Mise en relation avec partenariats, créateurs, et influenceurs, ainsi qu'optimisation de la visibilité et promotion de produits.</p>
            </div>
        </div>
        <!-- Service 4 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-computer" style="color: #ffffff;"></i></div>
                <h5>Services Techniques</h5>
                <p class="desc">Informatique personnalisée, création de musique "Libre de Droits," gestion des médias sociaux, et mise en place de la production vidéo.</p>
            </div>
        </div>
        <!-- Service 5 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0.3s">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i></div>
                <h5>Analyse et Rapports Personnalisés</h5>
                <p class="desc">Études mensuelles des statistiques, récapitulatif des données clés, et suivi du succès du projet.</p>
            </div>
        </div>
        <!-- Service 9 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0.6s">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-square-rss" style="color: #ffffff;"></i></div>
                <h5>Optimisation de Communication</h5>
                <p class="desc">Amélioration de la communication traditionnelle et numérique sur différents canaux.</p>
            </div>
        </div>
        <!-- Service 7 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-calendar-days" style="color: #ffffff;"></i></div>
                <h5>Organisation Administrative</h5>
                <p class="desc">Gestion des rendez-vous et agent dédié avec FAQ.</p>
            </div>
        </div>
        <!-- Service 8 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0.3s">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-tag"></i></div>
                <h5>Mise en Avant des Produits</h5>
                <p class="desc">Promotion de divers produits de créateurs.</p>
            </div>
        </div>
        <!-- Service 6 -->
        <div class="col-12 col-lg-4 res-margin wow fadeInUp" data-wow-offset="10" data-wow-duration="1s" data-wow-delay="0.6s">
            <div class="service-single">
                <div class="icon"><i class="fa-solid fa-brain" style="color: #ffffff;"></i></div>
                <h5>Soutien Psychologique</h5>
                <p class="desc">Fourniture de soutien émotionnel et psychologique.</p>
            </div>
        </div>
    </div>
</div>