<!-- Container Ends -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-6">
            <div class="section-title text-center">
                <h3>PARTENAIRES</h3>
            </div>
        </div>
    </div>
    <!-- Row and Scroller Wrapper Starts -->
    <div class="row owl-carousel owl-theme" id="clients-scroller" style="opacity: 1; display: block;">
        <div class="owl-wrapper-outer">
            <div class="owl-wrapper" style="left: 0px;">
                <div class="owl-item" style="width: 222px;">
                    <div class="client-item-wrapper">
                        <a href="https://tyrolium.fr/">
                            <img src="images/tyrolium.png" alt="">
                        </a>
                    </div>
                </div>

                <div class="owl-item" style="width: 222px;">
                    <div class="client-item-wrapper">
                        <a href="https://www.lafrenchtech-onelse.com/">
                            <img src="images/frenchtechlyon.png" alt="">
                        </a>
                    </div>
                </div>

                <div class="owl-item" style="width: 222px;">
                    <div class="client-item-wrapper">
                        <a href="https://www.auvergnerhonealpes.fr/">
                            <img src="images/auvergne-Rhone-Alphes.png" alt="">
                        </a>
                    </div>
                </div>

                <div class="owl-item" style="width: 222px;">
                    <div class="client-item-wrapper">
                        <a href="https://www.grandest.fr/">
                            <img src="images/grandest.png" alt="">
                        </a>
                    </div>
                </div>

                <div class="owl-item" style="width: 222px;">
                    <div class="client-item-wrapper">
                        <a href="https://www.linkedin.com/company/génération-ium/">
                            <img src="images/Generatium-ium.png" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>