<div class="container">

    <div class="section-title">
        <h3>ILS NOUS ONT DÉJÀ REJOINTS</h3>
    </div>
    <br>
    <div class="row justify-content-center">

        <div class="col-lg-6">
            <div class="member d-flex align-items-start">
                <div class="pic"><img src="images/image.png" class="img-fluid" alt=""></div>
                <div class="member-info">
                    <h4>AuroreTVv</h4>
                    <span>Streameuse</span>
                    <div class="social">
                        <a href="https://www.linkedin.com/in/aurore-pluquet-60aa53228/"><i class="fa-brands fa-linkedin-in" style="color: #ffffff;"></i></a>
                        <a href="https://twitter.com/AuroreTV_v"><i class="fa-brands fa-twitter" style="color: #ffffff;"></i></a>
                        <a href="https://www.instagram.com/auroretvv/"><i class="fa-brands fa-instagram" style="color: #ffffff;"></i></a>
                        <a href="https://www.youtube.com/@auroretvv"><i class="fa-brands fa-youtube" style="color: #ffffff;"></i></a>
                        <a href="https://www.twitch.tv/auroretvv"><i class="fa-brands fa-twitch" style="color: #ffffff;"></i></a>
                        <a href="https://www.tiktok.com/@aurore_vtubeuse"><i class="fa-brands fa-tiktok" style="color: #ffffff;"></i></a>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-lg-6 mt-4 mt-lg-0">
            <div class="member d-flex align-items-start">
                <div class="pic"><img src="images/doublet.png" class="img-fluid" alt=""></div>
                <div class="member-info">
                    <h4>DoubleT</h4>
                    <span>Streameur</span>
                    <div class="social">
                        <a href="https://twitter.com/Doublet_creator"><i class="fa-brands fa-twitter" style="color: #ffffff;"></i></a>
                        <a href="https://www.instagram.com/doublet_creator/"><i class="fa-brands fa-instagram" style="color: #ffffff;"></i></a>
                        <a href="https://www.youtube.com/channel/UCI7YjBRiSjhbzAi2pyVbxBw"><i class="fa-brands fa-youtube" style="color: #ffffff;"></i></a>
                        <a href="https://www.twitch.tv/doublet_creator"><i class="fa-brands fa-twitch" style="color: #ffffff;"></i></a>
                        <a href="https://www.tiktok.com/@doubletcreator"><i class="fa-brands fa-tiktok" style="color: #ffffff;"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start">
                <div class="pic"><img src="images/ma3wan.png" class="img-fluid" alt=""></div>
                <div class="member-info">
                    <h4>MA3WAN</h4>
                    <span>Youtubeur</span>
                    <div class="social">
                        <a href="https://linkedin.com/in/maëwan-marthelot-01744b203"><i class="fa-brands fa-linkedin-in" style="color: #ffffff;"></i></a>
                        <a href="https://instagram.com/maewanm"><i class="fa-brands fa-instagram" style="color: #ffffff;"></i></a>
                        <a href="https://www.youtube.com/c/MA3WAN/videos"><i class="fa-brands fa-youtube" style="color: #ffffff;"></i></a>
                    </div>
                </div>
            </div>
        </div>





        <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start">
                <div class="pic"><img src="images/ananastudio.png" class="img-fluid" alt=""></div>
                <div class="member-info">
                    <h4>AnanaStudio</h4>
                    <span>Youtubeur</span>
                    <div class="social">
                        <a href="https://www.youtube.com/channel/UCVr-bm49yG0Ipcy3jfRxvig"><i class="fa-brands fa-youtube" style="color: #ffffff;"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start">
                <div class="pic"><img src="images/rayquaconda.png" class="img-fluid" alt=""></div>
                <div class="member-info">
                    <h4>Rayquaconda</h4>
                    <span>Youtubeur</span>
                    <div class="social">
                        <a href="https://twitter.com/rayquacondaytb"><i class="fa-brands fa-twitter" style="color: #ffffff;"></i></a>
                        <a href="https://instagram.com/rayquacondaytb_off"><i class="fa-brands fa-instagram" style="color: #ffffff;"></i></a>
                        <a href="https://www.youtube.com/channel/UCeNemYwmIYDBnYSMV8F9cUg"><i class="fa-brands fa-youtube" style="color: #ffffff;"></i></a>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>